name: News_API
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  get: ^4.6.5
  url_launcher: ^6.1.5
  json_annotation: ^4.6.0
  cached_network_image: ^3.2.2
  dio_http_cache: ^0.3.0

dependency_overrides:
  json_serializable: ^6.5.1

dev_dependencies:
  json_serializable: ^6.3.2
  build_runner: ^2.2.1
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
